#ifndef _INKSMALLFROG_COMPILER_LEARNING_LEXER_WORDTYPE_
#define _INKSMALLFROG_COMPILER_LEARNING_LEXER_WORDTYPE_

typedef enum LexerWordType_{
  WORDTYPE_IDENTIFY = 256,
  WORDTYPE_INT,
  WORDTYPE_DOUBLE,
  WORDTYPE_UNARYOP,
  WORDTYPE_BINARYOP,
  WORDTYPE_BOOLUNARYOP,
  WORDTYPE_BOOLBINARYOP,
  WORDTYPE_NULL
}LexerWordType;

#endif
